# Generated by Django 4.1 on 2022-08-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="pub_date",
            field=models.DateField(verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="news",
            name="tag_ext",
            field=models.CharField(max_length=200, verbose_name="Тег внешний"),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.TextField(verbose_name="Название"),
        ),
    ]
