# Generated by Django 4.1 on 2022-08-26 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_news_pub_date_alter_news_tag_ext_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="tag_int",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="name",
        ),
        migrations.AddField(
            model_name="tag",
            name="news",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="app.news",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="TagNews",
        ),
    ]
