# Generated by Django 4.1 on 2022-08-26 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_news_tag_int_remove_tag_name_tag_news_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TagNews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tag",
            name="news",
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(through="app.TagNews", to="app.tag"),
        ),
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tagnews",
            name="news",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.news"
            ),
        ),
        migrations.AddField(
            model_name="tagnews",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.tag"
            ),
        ),
    ]
