# Generated by Django 4.1 on 2022-08-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_tagnews_remove_tag_news_news_tags_tag_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="pub_date",
            field=models.DateTimeField(verbose_name="Дата публикации"),
        ),
    ]
